version: '3.8'

services:
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-webserver
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    environment:
      - PYTHONPATH=/opt/airflow/dags
      - AIRFLOW__WEBSERVER__SECRET_KEY=key
      - AIRFLOW__WEBSERVER__AUTHENTICATE=True
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password
      - AIRFLOW__WEBSERVER__USER_NAME=admin
      - AIRFLOW__WEBSERVER__PASSWORD=admin
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://hive:hive@postgres:5432/metastore
    command: >
      bash -c "airflow db upgrade && airflow webserver"

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow-scheduler
    depends_on:
      - redis
      - postgres
      - airflow-webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY=key
      - PYTHONPATH=/opt/airflow/dags
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://hive:hive@postgres:5432/metastore
    command: >
      bash -c "airflow db upgrade && airflow scheduler"

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    container_name: service
    depends_on:
      - redis
      - mlflow  
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MLFLOW_TRACKING_URI=http://mlflow:5000 
    ports:
      - "5051:5051" 
    command: uvicorn app.main:app --host 0.0.0.0 --port 5051

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - postgres
 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://hive:hive@postgres:5432/metastore?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    
volumes:
  redis_data: 
  mlflow_artifacts:
  prometheus_data:
  grafana_data:
