version: '3.8'

services:
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - hive
      - mysql

  hive:
    image: bde2020/hive:2.3.0
    environment:
      HIVE_METASTORE_DB: "mysql" 
      MYSQL_HOST: "mysql"  
      MYSQL_PORT: "3306"
      MYSQL_USER: "hive"
      MYSQL_PASSWORD: "hive"
      MYSQL_DATABASE: "hive"
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    depends_on:
      - mysql
      - redis
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./mlflow/artifacts:/mlflow/artifacts
    depends_on:
      - mlflow
      - redis
  volumes:
    mlflow_artifacts: